### ISSUE TITLE
The Complement Objective Training Criterion

### ISSUE THREAD

**Issue by Canurd** [henry8527/COT#1]
Hi!
I was wondering if the function for the Complement Objective Training Criterion should be multiplied by -1/N (N being the total number of data) instead of 1/N, according to equation (2) in your paper?  Thank you very much!

**Comment by henry8527** [comment]
Hi, thanks for enjoying our paper and implementations. Due to the objective of Complement Entropy mentioned in equation (2) is maximized, we need to negate the equation (2) for using gradient descent with traditional training procedure.

**Comment by Canurd** [comment]
Yeah that makes sense. Thx!

**Comment by SunnyWangGitHub** [comment]
Hi! I want to ask if the COT loss during training is negative? This happened in my training.
