### ISSUE TITLE
Hi! I want to ask if the COT loss during training is negative?

### ISSUE THREAD

**Issue by SunnyWangGitHub** [henry8527/COT#2]
Hi! 
I want to ask if the COT loss during training is negative? This happened in my training.I trained on miniimagenet. backbone is  resnet18.Here is my partial log of loss.

Epoch 0 | Batch 0/150 | CE_Loss 5.306049 | COT_Loss -0.026461
Epoch 0 | Batch 10/150 | CE_Loss 5.239149 | COT_Loss -0.026450
Epoch 0 | Batch 20/150 | CE_Loss 5.132622 | COT_Loss -0.026385
Epoch 0 | Batch 30/150 | CE_Loss 5.024454 | COT_Loss -0.026249
Epoch 0 | Batch 40/150 | CE_Loss 4.927860 | COT_Loss -0.026061
Epoch 0 | Batch 50/150 | CE_Loss 4.845914 | COT_Loss -0.025851
Epoch 0 | Batch 60/150 | CE_Loss 4.776100 | COT_Loss -0.025639
Epoch 0 | Batch 70/150 | CE_Loss 4.716387 | COT_Loss -0.025441
Epoch 0 | Batch 80/150 | CE_Loss 4.664447 | COT_Loss -0.025261
Epoch 0 | Batch 90/150 | CE_Loss 4.618209 | COT_Loss -0.025102
Epoch 0 | Batch 100/150 | CE_Loss 4.576696 | COT_Loss -0.024960
Epoch 0 | Batch 110/150 | CE_Loss 4.539129 | COT_Loss -0.024832
Epoch 0 | Batch 120/150 | CE_Loss 4.505369 | COT_Loss -0.024717
Epoch 0 | Batch 130/150 | CE_Loss 4.474153 | COT_Loss -0.024612
Epoch 0 | Batch 140/150 | CE_Loss 4.446271 | COT_Loss -0.024514
Epoch 1 | Batch 0/150 | CE_Loss 4.031545 | COT_Loss -0.023097
Epoch 1 | Batch 10/150 | CE_Loss 4.008976 | COT_Loss -0.023048
Epoch 1 | Batch 20/150 | CE_Loss 3.983290 | COT_Loss -0.022999
Epoch 1 | Batch 30/150 | CE_Loss 3.973501 | COT_Loss -0.022962
Epoch 1 | Batch 40/150 | CE_Loss 3.961818 | COT_Loss -0.022922
Epoch 1 | Batch 50/150 | CE_Loss 3.948828 | COT_Loss -0.022878
Epoch 1 | Batch 60/150 | CE_Loss 3.936359 | COT_Loss -0.022836
Epoch 1 | Batch 70/150 | CE_Loss 3.925749 | COT_Loss -0.022795
Epoch 1 | Batch 80/150 | CE_Loss 3.917677 | COT_Loss -0.022755
Epoch 1 | Batch 90/150 | CE_Loss 3.911425 | COT_Loss -0.022715
Epoch 1 | Batch 100/150 | CE_Loss 3.902944 | COT_Loss -0.022675
Epoch 1 | Batch 110/150 | CE_Loss 3.893958 | COT_Loss -0.022635
Epoch 1 | Batch 120/150 | CE_Loss 3.885621 | COT_Loss -0.022596
Epoch 1 | Batch 130/150 | CE_Loss 3.876229 | COT_Loss -0.022561
Epoch 1 | Batch 140/150 | CE_Loss 3.866470 | COT_Loss -0.022528
Epoch 2 | Batch 0/150 | CE_Loss 3.611611 | COT_Loss -0.021999
Epoch 2 | Batch 10/150 | CE_Loss 3.717456 | COT_Loss -0.021929
Epoch 2 | Batch 20/150 | CE_Loss 3.759048 | COT_Loss -0.021937
Epoch 2 | Batch 30/150 | CE_Loss 3.764372 | COT_Loss -0.021923
Epoch 2 | Batch 40/150 | CE_Loss 3.753896 | COT_Loss -0.021913
Epoch 2 | Batch 50/150 | CE_Loss 3.747862 | COT_Loss -0.021900
Epoch 2 | Batch 60/150 | CE_Loss 3.740335 | COT_Loss -0.021885
Epoch 2 | Batch 70/150 | CE_Loss 3.732566 | COT_Loss -0.021878
Epoch 2 | Batch 80/150 | CE_Loss 3.727187 | COT_Loss -0.021865
Epoch 2 | Batch 90/150 | CE_Loss 3.720871 | COT_Loss -0.021853

**Comment by henry8527** [comment]
Yes, since we have negated the complement entropy loss for minimizing it.

**Comment by SunnyWangGitHub** [comment]
> Yes, since we have negated the complement entropy loss for minimizing it.

understood. thank you very much!
