### ISSUE TITLE
Negative sign of the loss

### ISSUE THREAD

**Issue by bckim1318** [henry8527/COT#3]
I think this code doesn't have negative sign of the loss explained in your paper.
I think xlnx should be always below zero if 0<x<=1.
And yij/(1-yig) should be larger than 0, and below 1.
Then, with the negative sign, I think the loss should be positive but training process shows it's negative.
Is there any point I missed in your paper?

**Comment by bckim1318** [comment]
I think loss with postive sign seems correct.

**Comment by henry8527** [comment]
Since we have negated the complement entropy loss for minimizing it.
