### ISSUE TITLE
 just add the two loss together 

### ISSUE THREAD

**Issue by GuoQingqing** [henry8527/COT#6]
I have a question.There is one more step backward and optimize. Why don't you just add the two loss together and do the back propagation?

**Comment by Kurumi233** [comment]
Have you conducted an experiment this way? How about the results?

**Comment by henry8527** [comment]
Hi both, you can check our response here https://openreview.net/forum?id=HyM7AiA5YX&noteId=HJlOtAKta7

**Comment by Kurumi233** [comment]
OK, thanks.
